prlib.lo: /home/liuyue01/git/envbuild/mpp_deploy/soft/php-5.2.4/ext/prlib/prlib.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/liuyue01/git/envbuild/mpp_deploy/soft/php-5.2.4/ext/prlib $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/liuyue01/git/envbuild/mpp_deploy/soft/php-5.2.4/ext/prlib/prlib.c -o prlib.lo 
$(phplibdir)/prlib.la: ./prlib.la
	$(LIBTOOL) --mode=install cp ./prlib.la $(phplibdir)

./prlib.la: $(shared_objects_prlib) $(PRLIB_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_prlib) $(PRLIB_SHARED_LIBADD)

